@ApiUrl = http://localhost:5500

GET {{ApiUrl}}/pois

###

GET {{ApiUrl}}/pois/ver/1

###

@Distancia = 10
@CoordX = 20
@CoordY = 10

GET {{ApiUrl}}/pois/buscar?d={{distancia}}&x={{CoordX}}&y={{CoordY}}

###

POST {{ApiUrl}}/pois
Content-Type: application/json

{
  "Name": "Ponto teste",
  "CoordX": 5,
  "CoordY": 2
}

###